import blogImage1 from './images/blogImage1.jpg'
import blogImage2 from './images/blogImage2.jpg'
import blogImage3 from './images/blogImage3.jpg'

import productImage from './images/productImage.jpg';

export const blogDetails = [
  {
    blogIndex: 1,
    img: blogImage1,
    title: "Lorem ipsum dolor sit amet,",
    description:
      "consectetur adipiscing elit. Vestibulum consequat enim ut lectus pellentesque ",
    date: "October 13,2023",
  },
  {
    blogIndex: 2,
    img: blogImage2,
    title: "Lorem ipsum dolor sit amet,",
    description:
      "Gallstones are the hardened substance that gets deposited inside the gallbladder.",
    date: "October 13,2023",
  },
  {
    blogIndex: 3,
    img: blogImage3,
    title: "Lorem ipsum dolor sit amet",
    description:
      "Several researches prove that our eyes are implicated in attracting.  ",
    date: "October 13,2023",
  },
  {
    blogIndex: 4,
    img: blogImage1,
    title: "Lorem ipsum dolor sit amet",
    description:
      "Several researches prove that our eyes are implicated in attracting. ",
    date: "October 13,2023",
  },
  {
    blogIndex: 5,
    img: blogImage2,
    title: "Lorem ipsum dolor sit amet",
    description:
      "Several researches prove that our eyes are implicated in attracting.",
    date: "October 13,2023",
  },
  {
    blogIndex: 6,
    img: blogImage3,
    title: "Lorem ipsum dolor sit amet",
    description:
      "consectetur adipiscing elit. Vestibulum consequat enim ut lectus ",
    date: "October 13,2023",
  },
];

export const productsDetails = [
  {
    prodIndex: 1,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 2,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 3,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 4,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 5,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 6,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 7,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 8,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 9,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 10,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 11,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 12,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 13,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 14,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 15,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 16,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 17,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 1,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 1,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
  {
    prodIndex: 1,
    prodImage: productImage,
    category: "category of the product",
    prodName: "Product Name",
    star: "3",
    oldPrice: 121,
    newPrice: 54,
  },
];
